version: '3.7'

services:

  db:
    image: 'postgres:11'
    container_name: posgresqldb
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - parent-demo-todo-db-volume:/var/lib/posgresql/data

    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=SuperSecret
      - POSTGRES_DB=todoappdb


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 9090:80
    volumes:
      - parent-demo-todo-pgadmin-volume:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=pgadminpassword

volumes:
  parent-demo-todo-db-volume:
  parent-demo-todo-pgadmin-volume:


networks:
  default:
    name: parent-demo-todo-network